env:
  browser: true
  node: true

plugins:
  - react

extends:
  - eslint:recommended
  - plugin:react/recommended

settings:
  react:
    pragma: h

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  no-console: 0
  react/prop-types: 0
  react/no-unknown-property: 0
