env:
  browser: true
  node: true

plugins:
  - react

extends:
  - eslint:recommended
  - plugin:react/recommended

settings:
  react:
    pragma: h

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  semi: 2
  curly: 2
  no-shadow: 2
  no-var: 2
  prefer-const: 2
  linebreak-style: 2
  quotes: [2, 'single']
  no-console: 0
  react/prop-types: 0
  react/no-unknown-property: 0
