# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_listing_apply_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='poster_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
