# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('FS', 'Fullstack'), ('DO', 'Devops'), ('MB', 'Mobile')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('role_title', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_link', models.CharField(blank=True, max_length=300)),
                ('company_image', models.CharField(blank=True, max_length=300)),
                ('company_base', models.CharField(blank=True, max_length=100)),
                ('company_desc', models.TextField(blank=True)),
                ('company_size', models.IntegerField(null=True)),
                ('company_funding', models.CharField(blank=True, max_length=50)),
                ('company_tech', models.CharField(blank=True, max_length=100)),
                ('role_desc', models.TextField(blank=True)),
                ('role_position', models.CharField(blank=True, max_length=50)),
                ('role_tech', models.CharField(blank=True, max_length=100)),
                ('role_compensation', models.CharField(blank=True, max_length=100)),
                ('apply_link', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category')),
            ],
        ),
    ]
