# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20170712_1219'), ('main', '0003_auto_20170712_1309'), ('main', '0004_tag'), ('main', '0005_listing_poster_email'), ('main', '0006_auto_20170714_1617'), ('main', '0007_auto_20170714_1709'), ('main', '0008_auto_20170714_1729'), ('main', '0009_auto_20170714_1731'), ('main', '0010_listing_apply_email'), ('main', '00011_auto_20170714_1900'), ('main', '0012_auto_20170714_1908'), ('main', '0013_auto_20170714_1921'), ('main', '0014_auto_20170727_1521'), ('main', '0015_auto_20170727_1527'), ('main', '0016_auto_20170727_1550'), ('main', '0017_application'), ('main', '0018_auto_20170916_1358'), ('main', '0019_listing_users'), ('main', '0020_auto_20171001_1921'), ('main', '0021_auto_20171008_2259'), ('main', '0022_remove_listing_users'), ('main', '0023_auto_20171008_2346'), ('main', '0024_user'), ('main', '0025_auto_20171009_1357'), ('main', '0026_listing_confirmed'), ('main', '0027_auto_20171107_0253'), ('main', '0028_auto_20171107_1529'), ('main', '0029_application_notes')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('initial', 'No initial response yet'), ('need', 'I need to respond'), ('await', 'Awaiting response'), ('scheduled', 'Interview scheduled'), ('offer', 'Got offer'), ('declined', 'Declined'), ('rejected', 'Got Rejected')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(default='default company', max_length=200)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('role', models.CharField(default='default role', max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
