# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('role_title', models.CharField(max_length=50)),
                ('role_subtitle', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('company_link', models.CharField(max_length=300)),
                ('company_desc', models.TextField()),
                ('company_size', models.IntegerField(default=0)),
                ('company_funding', models.CharField(max_length=50)),
                ('company_tech', models.CharField(max_length=100)),
                ('role_desc', models.TextField()),
                ('role_position', models.CharField(max_length=50)),
                ('role_tech', models.CharField(max_length=100)),
                ('role_compensation', models.CharField(max_length=100)),
                ('apply_link', models.CharField(max_length=300)),
            ],
        ),
    ]
