# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_squashed_0029_application_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
