# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='company_base',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='company_image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
