# Generated by Django 2.0 on 2017-12-08 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171203_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('initial', 'To Do'), ('initial', 'No initial response yet'), ('need', 'I need to respond'), ('await', 'Awaiting response'), ('scheduled', 'Interview scheduled'), ('offer', 'Got offer'), ('declined', 'Declined'), ('rejected', 'Got Rejected')], max_length=50),
        ),
    ]
