# Generated by Django 2.0 on 2017-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171208_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('todo', 'To Do'), ('initial', 'No initial response yet'), ('need', 'I need to respond'), ('await', 'Awaiting response'), ('scheduled', 'Interview scheduled'), ('offer', 'Got offer'), ('declined', 'Declined'), ('rejected', 'Got Rejected')], max_length=50),
        ),
    ]
