# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170709_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='apply_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_funding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_tech',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_compensation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_tech',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
