# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='poster_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
