# Generated by Django 2.0 on 2018-01-03 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
