# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170709_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='company_size',
            field=models.IntegerField(blank=True),
        ),
    ]
