# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170714_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='role_position',
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_type',
            field=models.CharField(blank=True, choices=[('F', 'Full time'), ('C', 'Contract')], max_length=1),
        ),
    ]
