# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170709_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='role_subtitle',
        ),
    ]
