# Generated by Django 2.0 on 2018-01-10 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reminder_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='day',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='hour',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date_activation',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
