# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170714_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='role_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='role_remote',
            field=models.NullBooleanField(),
        ),
    ]
