# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='company_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_size',
            field=models.IntegerField(null=True),
        ),
    ]
