# Generated by Django 2.0 on 2018-01-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180110_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='completed',
        ),
    ]
