# Generated by Django 2.0 on 2018-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_reminder_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
