# Generated by Django 2.0 on 2018-01-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reminder_in_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
