# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170714_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default=main.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
