# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170714_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_base',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_funding',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_tech',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='poster_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_compensation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_remote',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_tech',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_type',
            field=models.CharField(choices=[('F', 'Full time'), ('C', 'Contract')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Listing'),
        ),
    ]
