# Generated by Django 2.0 on 2018-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_analytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
