# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170727_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='poster_email',
            field=models.EmailField(max_length=254),
        ),
    ]
