# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20170727_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='apply_email',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
