# Generated by Django 2.0 on 2018-01-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='company_title',
            new_name='company_name',
        ),
    ]
