# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
