# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20170916_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
