# Generated by Django 2.0 on 2018-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='last_used',
            field=models.DateTimeField(),
        ),
    ]
