# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_listing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='company_size',
            field=models.CharField(max_length=50),
        ),
    ]
