# Generated by Django 2.0 on 2018-01-14 17:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180113_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default=main.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
