# Generated by Django 2.0 on 2018-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180114_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='enabled',
        ),
        migrations.AddField(
            model_name='listing',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
