# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20171001_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
    ]
