# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171008_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='users',
        ),
    ]
