# Generated by Django 2.0 on 2018-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='salary',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
