# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_remove_listing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('initial', 'No initial response yet'), ('need', 'I need to respond'), ('await', 'Awaiting response'), ('scheduled', 'Interview scheduled'), ('offer', 'Got offer'), ('declined', 'Declined'), ('rejected', 'Got Rejected')], max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(related_name='applications', through='main.Application', to=settings.AUTH_USER_MODEL),
        ),
    ]
