# Generated by Django 2.0 on 2018-01-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180123_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='test',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
