# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
