# Generated by Django 2.0 on 2018-01-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_listing_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='test',
        ),
    ]
