# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_listing_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='application',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
