export default [
  {
    id: 1,
    role: 'Frontend Developer',
    company: 'Avocado Jobs',
    stage: 'scheduled',
    salary: '$100k',
    link: 'https://stackoverflow.com/jobs?demo-job-link',
    notes: 'React.js',
    date: '2017-11-10',
  },
  {
    id: 2,
    role: 'Backend Engineeer',
    company: 'Acme Corporation',
    stage: 'need',
    salary: '$80k',
    link: 'https://jobs.github.com/?demo-job-link',
    notes: 'Recommendation from Wile E.\nSeries A $2m',
    date: '2017-11-02',
  },
  {
    id: 3,
    role: 'Security Engineer',
    company: 'E Corp',
    stage: 'initial',
    salary: '$135k',
    link: 'https://remoteok.io/?demo-job-link',
    notes: 'Blockchain tech',
    date: '2017-12-12',
  },
  {
    id: 4,
    role: 'Software Engineer',
    company: 'Stark Industries',
    stage: 'need',
    salary: '$115k',
    link: 'https://jobs.github.com/?stark-industries-job-link',
    notes: 'Defense industry',
    date: '2017-12-19',
  },
  {
    id: 5,
    role: 'Backend Engineer',
    company: 'Zorg Industries',
    stage: 'initial',
    salary: '$130k',
    link: 'https://jobs.github.com/?zorg-industries-job-link',
    notes: '',
    date: '2017-12-5',
  },
  {
    id: 6,
    role: 'Mobile Engineer',
    company: 'Tyrell Corporation',
    stage: 'declined',
    salary: '$175k',
    link: 'https://jobs.github.com/?offworld-demo-job-link',
    notes: 'Android',
    date: '2017-12-2',
  },
  {
    id: 7,
    role: 'Game Engine Software Engineer',
    company: 'Gregarious Simulation Systems',
    stage: 'rejected',
    salary: '$120k',
    link: 'https://jobs.github.com/?gss-job-link',
    notes: 'OASIS',
    date: '2017-11-21',
  },
  {
    id: 8,
    role: 'Frontend Engineer',
    company: 'Monsters, Inc.',
    stage: 'await',
    salary: '$112k',
    link: 'https://jobs.github.com/?monsters-inc-job-link',
    notes: '',
    date: '2017-12-1',
  },
  {
    id: 9,
    role: 'Game Development Engineer',
    company: 'Innovative Online Industries',
    stage: 'todo',
    salary: '',
    link: 'https://jobs.github.com/?ioi-job-link',
    notes: '',
    date: '2017-12-29',
  },
  {
    id: 10,
    role: 'Software Engineer',
    company: 'Massive Dynamic',
    stage: 'offer',
    salary: '$190k',
    link: 'https://jobs.github.com/?massive-dynamic-job-link',
    notes: 'Need to sign many NDAs',
    date: '2017-12-29',
  },
  {
    id: 11,
    role: 'Software Engineer',
    company: 'Megadodo Publications',
    stage: 'need',
    salary: '$160k',
    link: 'https://jobs.github.com/?megadodo-job-link',
    notes: 'Remote',
    date: '2017-12-9',
  },
  {
    id: 12,
    role: 'Embedded Engineer',
    company: 'Sirius Cybernetics Corporation',
    stage: 'todo',
    salary: '',
    link: 'https://jobs.github.com/?sirius-cybernetics-job-link',
    notes: 'Remote',
    date: '2017-12-29',
  },
];
